### ISSUE TITLE
SummaryList output for screenreaders

### ISSUE THREAD

**Issue by paulodeon** [x-govuk/govuk-components#402]
We had some feedback from the Digital Accessibility Centre regarding the output of `GovukComponent::SummaryListComponent::ActionComponent`

> Some link text was formatted in a way that weas difficult for screen reader users to  understand. 
>
> The ‘change’ link within the ‘Your name’ row within the summary list is formatted such that  screen reader software does not reliably interpret it. The space between the link text and  the hidden text is not recognised by some screen reader software, and thus will not be  announced properly to screen reader users. For example, ‘Change your name’ is interpreted  as ‘Changeyour name’.
> 
> Current output
```html
<a class="govuk-link" href="/referrals/3/referrer 
name/edit?return_to=%2Freferrals%2F3%2Freferrer"> 
Change <span class="govuk-visually-hidden">your name</span> 
</a> 
```
> 
> Solution
> 
> For reliable screen reader parsing of link text, we recommend placing a non-breaking space  character in the visually-hidden text using the HTML entity “&nbsp;”. Placing the non breaking space within the visually hidden text prevents a space from being placed at the end  of the visible link. The trailing space before the visually hidden <span> can then be removed  to prevent some browsers from interpreting two spaces adjacent to each other. 
>
> 
```html
<a class="govuk-link" href="/referrals/3/referrer 
name/edit?return_to=%2Freferrals%2F3%2Freferrer"> 
Change<span class="govuk-visually-hidden">&nbsp;your name</span> </a>
```

Is this something we'd accept into the library? 

Happy to create a PR if so

**Comment by peteryates** [comment]
Ah, interesting!

Yeah I'd be more than happy to accept it - having to do it manually definitely feels a bit clunky. I think it should at least be a [global config option](https://github.com/DFE-Digital/govuk-components/blob/main/lib/govuk/components/engine.rb#L102), but perhaps should be an argument too?

**Comment by frankieroberto** [comment]
This is also being tracked upstream here by the Design System team: https://github.com/alphagov/govuk-frontend/issues/2547

**Comment by peteryates** [comment]
I think this is solved now.
