### ISSUE TITLE
Add task list component

### ISSUE THREAD

**Issue by frankieroberto** [x-govuk/govuk-components#425]
This is a placeholder issue where we can discuss how best to add the Task list component which [has now been added to govuk-frontend](https://github.com/alphagov/govuk-frontend/pull/2261) but not yet released.

**Comment by frankieroberto** [comment]
One complication of the task list is that the "status" can either contain raw text (or HTML) or it can contain a tag component.

The API for the nunjucks macro looks like this:

```nunjucks
{{ govukTaskList({
  items: [
    {
      title:
        {
          text: "Company Directors"
        },
      href: "#",
      status: {
        text: "Completed"
      }
    },
    {
      title:
        {
          text: "Registered company details"
        },
      href: "#",
      status: {
        tag: {
          text: "Incomplete",
          classes: "govuk-tag--blue"
        }
      }
    }
  ]
}) }}
```

The ruby helper could be quite similar, but with shortcuts for setting colour?

```ruby
govuk_task_list(items: [
  { 
    title: "Company details", 
    href: "#", 
    status: { text: "Completed" } 
  }, { 
    title: "Registered company details", 
    href: "#", 
    status: { tag: { text:"Completed", colour: "blue" } }
  }
])
```
 
Alternatively (or in addition?) it could support "slots" using the block syntax:

```ruby

govuk_task_list do |task_list|
  task_list.with_item(title: "Company details", href: "#", status: { text: "Completed" })
  task_list.with_item(title: "Registered company details", href: "#", status: { tag: { text:"Completed", colour: "blue" })
end
```

Any thoughts @peteryates @paulrobertlloyd?

**Comment by peteryates** [comment]
I didn't realise it had progressed this far, how exciting.

Your proposed syntax looks great to me, supporting both styles should be straightforward - the approach taken by the summary list and table works well.
