### ISSUE TITLE
Support other design systems

### ISSUE THREAD

**Issue by tvararu** [x-govuk/govuk-components#440]
Like https://github.com/x-govuk/govuk-form-builder/pull/127, is there any appetite to support the `config.brand` option in this library as well?

We're using [the form builder option in a `nhsuk-frontend` project](https://github.com/nhsuk/record-childrens-vaccinations/pull/327), and while we had to patch over the JS for the radio buttons, the rest of it seems to work. Having that option was a big help.

If it sounds good, maybe I could make a start on it.

**Comment by peteryates** [comment]
Yeah absolutely - I'd be more than happy to have that functionality here too.
