### ISSUE TITLE
SVG attribute `viewBox` not correctly capitalised

### ISSUE THREAD

**Issue by lfdebrux** [x-govuk/govuk-components#459]
### Description of issue

While swapping out some hardcoded Design System HTML for the (excellent) view components in this gem, I noticed a small regression; in the hardcoded HTML the crown SVG has an attribute `viewBox`, while in the ERB provided in the gem it is called `viewbox`:

https://github.com/x-govuk/govuk-components/blob/30340f72ecb42086fc8ae641c3abef1a751f4414/app/components/govuk_component/header_component.html.erb#L11

https://github.com/x-govuk/govuk-components/blob/30340f72ecb42086fc8ae641c3abef1a751f4414/app/components/govuk_component/footer_component.html.erb#L29

According to Google SVG attributes are case sensitive, and this one should be kebab case (for references, [MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox), this [tweet about the issue with replies from frontend experts](https://twitter.com/rem/status/759744091538137091?s=20), and this [article stating that SVG is case-sensitive](https://thenewcode.com/1151/Understanding-the-SVG-viewBox#:~:text=Also%20note%20the%20capitalization%20of,it%20is%20to%20be%20recognized.&text=You%20might%20think%20of%20this,the%20elements%20inside%20an%20SVG.)).

I'm not sure if this is actually an issue in any browsers; I can't see a difference in Chrome; but since the attribute is correctly capitalised [in the latest release of GOV.UK Frontend](https://github.com/alphagov/govuk-frontend/blob/v4.7.0/package/govuk/components/header/template.njk#L27), I thought I should flag it up.

### Suggested fix

Replace `viewbox` with `viewBox` in SVG tags.

**Comment by frankieroberto** [comment]
@lfdebrux opps! Thanks for spotting this. Fixed in #461
