### ISSUE TITLE
Slightly out-of-date gem and node package instructions in the upgrade section of the 5.0.0 release notes

### ISSUE THREAD

**Issue by benilovj** [x-govuk/govuk-components#482]
I think the gem and node package instructions [in the 5.0.0 release notes](https://github.com/x-govuk/govuk-components/releases/tag/v5.0.0) need updating:

<img width="1311" alt="image" src="https://github.com/x-govuk/govuk-components/assets/23801/b98e61fb-3ac9-457e-a26c-1926f4dc40da">

```
gem "govuk-components", "~> 5.0.0"
```
and
```
"govuk-frontend": "5.0.0",
```

**Comment by frankieroberto** [comment]
Opps! 🤦  Fixed, thanks!
