### ISSUE TITLE
Update breadcrumbs to accept an array, deprecate hash argument

### ISSUE THREAD

**Issue by frankieroberto** [x-govuk/govuk-components#508]
The [Breadcrumbs component](https://govuk-components.netlify.app/components/breadcrumbs/) currently requires the links to be specified using a hash argument:

```erb
<%= govuk_breadcrumbs(breadcrumbs: {
  "Home" => "/", 
  "Level one page" => "/", 
  "Level two page" => "/" 
}) %>
```

Whilst in Ruby 1.9+, hashes do have an order, they're not really designed to hold data where the order is significant – for example, adding a new item to the hash at any point other than at the end is not easy.

Additionally, the hash structure means that there’s no easy way to add additional attributes to any of the individual breadcrumb items. (Although this requirement might be rare?)

Switching to an array might be preferable - but that the expense of being slightly longer:

```erb
<%= govuk_breadcrumbs(breadcrumbs: [
  {text: "Home", path: "/", html_attributes: {class: "app-breadcrumbs__link--home"}, 
  {text: "Level one page", path: "/"}, 
  {text: "Level two page", path: "/"} 
]) %>
```

Alternatively we could follow the convention of `link_to` and nested arrays where the link text comes first, followed by the path, and then a hash of any other attributes:

```erb
<%= govuk_breadcrumbs(breadcrumbs: [
  ["Home", "/", {html_attributes: {class: "app-breadcrumbs__link--home"}}], 
  ["Level one page", "/"], 
  ["Level two page", "/"] 
]) %>
```

We could make this backwards-compatible by supporting both hashes and arrays initially, but marking the hashes as deprecated?

**Comment by peteryates** [comment]
I'm not a huge fan of requiring arrays where the placement of arguments is important, I'd prefer an array of hashes for that. I think the current implementation of accepting an array of links is cleaner than the above though:

```ruby
  govuk_breadcrumbs(breadcrumbs: [
    govuk_breadcrumb_link_to("Home", "/"),
    govuk_breadcrumb_link_to("Level one page", "/"),
    govuk_breadcrumb_link_to("Level two page", "/")
  ])
```

This allows for all the desired customisability. Perhaps [this example](https://govuk-components.netlify.app/components/breadcrumbs/#breadcrumbs-from-an-array-of-links) should be first in the docs?

**Comment by frankieroberto** [comment]
> I'm not a huge fan of requiring arrays where the placement of elements is important, I'd prefer an array of hashes for that. I think the current implementation of accepting an array of links is cleaner than the above though

Doh, I didn’t even spot that this was an option (even though it’s in the documentation 🤦)! This feels more intuitive to me than the hash syntax.

I think we can close this issue for now.
