### ISSUE TITLE
Previews for Components

### ISSUE THREAD

**Issue by Nitemaeric** [x-govuk/govuk-components#512]
The [previews documentation](https://viewcomponent.org/guide/previews.html) details how to setup previews similar to action mailer previews, in a contained environment.

The `GovukComponent::FooterComponent` component breaks the guidelines of not relying on the `controller` during initialisation.

![CleanShot 2024-02-28 at 12 54 01](https://github.com/x-govuk/govuk-components/assets/4231530/b9b80f0a-8329-4663-8bd2-4c7b1ccd1e4d)

Upon investigation, the [govuk_footer_link_to](https://github.com/x-govuk/govuk-components/blob/main/app/components/govuk_component/footer_component.rb#L70) calls within [build_meta_links](https://github.com/x-govuk/govuk-components/blob/main/app/components/govuk_component/footer_component.rb#L25) are the source of this error.

The [link_to](https://github.com/x-govuk/govuk-components/blob/main/app/components/govuk_component/footer_component.rb#L85) call on line 85 seems to be fine though. My initial assumption is that `ViewComponent` defines `link_to` somewhere which is separate than the `link_to` referenced within our view helpers.

We have created a custom `FooterComponent`, in our repo [here](https://github.com/DFE-Digital/itt-mentor-services/pull/315), that inherits from `GovukComponent::FooterComponent`.

Could we move the presentation logic into the `erb` template itself?

**Comment by peteryates** [comment]
Interesting. Not quite sure what's going on here, I'll take a closer look.

**Comment by peteryates** [comment]
Ah, so I think it's falling foul because it's building the copyright content inside `#initialize` rather than when the component's rendered.

@Nitemaeric - would you mind trying to render with the above patch?
