### ISSUE TITLE
Notification banner: with_heading can't generate heading tags

### ISSUE THREAD

**Issue by DavidBiddle** [x-govuk/govuk-components#531]
The notification banner's `with_heading` method will always produce a div with the class `#{brand}-notification-banner__heading`. This is ideal for the case where the heading is the only content in the banner (because the content isn't actually a heading semantically, just large text):

```html
<div class="govuk-notification-banner" role="region" aria-labelledby="govuk-notification-banner-title" data-module="govuk-notification-banner">
  <div class="govuk-notification-banner__header">
    <h2 class="govuk-notification-banner__title" id="govuk-notification-banner-title">
      Important
    </h2>
  </div>
  <div class="govuk-notification-banner__content">
    <p class="govuk-notification-banner__heading">
      You have 7 days left to send your application.
      <a class="govuk-notification-banner__link" href="#">View application</a>.
    </p>
  </div>
</div>
```

However, if there's also other, non-heading content in the banner, we'd expect the heading to be a heading element, since it's semantically a heading for the content below:

```html
<div class="govuk-notification-banner govuk-notification-banner--success" role="alert" aria-labelledby="govuk-notification-banner-title" data-module="govuk-notification-banner">
  <div class="govuk-notification-banner__header">
    <h2 class="govuk-notification-banner__title" id="govuk-notification-banner-title">
      Success
    </h2>
  </div>
  <div class="govuk-notification-banner__content">
    <h3 class="govuk-notification-banner__heading">
      Training outcome recorded and trainee withdrawn
    </h3>
    <p class="govuk-body">Contact <a class="govuk-notification-banner__link" href="#">example@department.gov.uk</a> if you think there’s a problem.</p>
  </div>
</div>
```

(code examples taken from the [Design system docs for the notification banner component](https://design-system.service.gov.uk/components/notification-banner/)).

As things stand, if a user calls this component with both `with_heading` and a block, the generated code will fail WCAG 1.3.1 Info and Relationships (Level A), because the component would have a visible heading which isn't semantically marked up.

## Possible solutions
I can think of a few possible ways tro deal with this (there are probably others).

### 1. Leave things as they are and encourage people to use the block syntax
The govuk-frontend nunjucks macro lets you pass in an arbitrary block of HTML, which this implementation also allows. So users can manually pass the heading into the component:

```erb
<%= govuk_notification_banner(blah) do %>
  <h3 class="govuk-notification-banner__heading">
    Training outcome recorded and trainee withdrawn
  </h3>
  <p class="govuk-body">Contact <a class="govuk-notification-banner__link" href="#">example@department.gov.uk</a> if you think there’s a problem.</p>
<% end %>
```

This works, but I'm not sure it's intuitive for users - I think they'd probably expect (as our team did initially) `with_heading` to generate a heading element.

### 2. Get rid of the `with_heading` helper
The idea here would be to make the API more like the nunjucks macro - so users always have to pass in the markup for the heading, whether it's the fake div heading or a semantic one. This would probably be the simplest code change for this library, but it's annoying for anyone who's currently using `with_heading` and I'm sure there would be complexities around deprecation etc.

### 3. Make the `with_heading` helper generate the heading tag automatically
We could change the way the heading generation works so that it automatically uses a heading tag if the user has provided block content to the component, and uses a `div` if they haven't. This has the advantage of 'just working' without the user having to think about it, but on the other hand some users might be surprised by the change to the generated HTML. Presumably the heading tag would be `h#{title_heading_level + 1`, or `div` if `title_heading_level` is 6.

### 4. Add an optional `tag` parameter to `with_heading`
We could add an optional `tag` or `heading_level` parameter to the `with_heading` helper, so that the user can easily customise the heading:
```erb
<%= govuk_notification_banner(blah) do |banner| %>
  <% banner.with_heading(text: "Training outcome recorded and trainee withdrawn", tag: "h3")) %>
  <p class="govuk-body">Contact <a class="govuk-notification-banner__link" href="#">example@department.gov.uk</a> if you think there’s a problem.</p>
<% end %>
```
This would return `div` if not specified by the user. This has the advantage of not changing anyone's existing HTML, and is the most flexible, but it does require people to remember to set it.

**Comment by DavidBiddle** [comment]
If you've got a preference on any of these solutions I'd be happy to try and implement - just let me know!

**Comment by DavidBiddle** [comment]
I've got some capacity to work on this in the next few days, so I'm going to have a go. Option 4 looks good to me, so I'll start with that for now.

**Comment by peteryates** [comment]
So sorry I missed this report when it was made, my GitHub notifications are carnage at the moment! 😞 

I totally agree, option 4 seems most sensible to me. Just switching the ` tag.div(**html_attributes) ` to `content_tag(tag, **html_attributes)` in the Heading component looks like it should you most of the way.

Would be more than happy to receive a PR on this ❤️

**Comment by DavidBiddle** [comment]
Thanks @peteryates - no worries about missing it (would only have got to it today anyway) and good suggestion on using `content_tag`!
